flushの挙動の改善・テストの導入etc
herp-inc/herp-logger pull request #30
Opened 2022-11-10 09:15 UTC by fumieval

* flushを呼び出すとLoggerSetのflushが呼ばれるが、キューに積まれている書き込み処理に影響を及ぼさないため扱いにくい挙動である。flushを呼ぶとresource-poolの中を一旦流すようにする

2022-11-10 10:07 UTC, fumieval commented
cleanupを呼ばずに終了した場合は対処が難しいので、とりあえずそれが想定した挙動です

2022-11-10 10:16 UTC, fumieval commented on src/Herp/Logger.hs
> -        -- FIXME: Multi transports writing to the same file occurs duplicated characters like "mmeessssaaggee"
同じLoggerSetを使っている限り起こり得ない挙動なので、単純にコメントの間違いだと思います(私が入社する前のコードなので実態は不明)

2022-11-11 09:01 UTC, ruicc requested changes

2022-11-11 10:03 UTC, fumieval commented on src/Herp/Logger.hs
> +                destroyAllResources thPool
確かに、キューが空になるまで待つのは好ましくないのでその部分は消しました

2022-11-11 10:15 UTC, ruicc approved these changes
LGTM!

2022-11-14 02:23 UTC, merged